# Dataset configurations
preprocessing:
  audio:
    sample_rate: 16000
    max_length: 10  # seconds
    normalize: true
  image:
    size: [48, 48]
    channels: 1  # grayscale
  text:
    max_length: 50
    tokenizer: "bert-base-uncased"

augmentation:
  train:
    image:
      horizontal_flip_prob: 0.5
      rotation_degrees: 5
      translate: [0.05, 0.05]
      normalize_mean: [0.5]
      normalize_std: [0.5]
    audio:
      pitch_shift_range: [-2, 2]
      speed_change_range: [0.9, 1.1]
      noise_factor: 0.005
  test:
    image:
      normalize_mean: [0.5]
      normalize_std: [0.5]

data_loading:
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  batch_size:
    train: 32
    test: 64

paths:
  processed_data: "data/processed"
  raw_data: "data/raw"
  fer2013: "data/processed/fer2013.csv"
  expw: "data/processed/expw.csv"
  ravdess: "data/processed/ravdess.csv"
  goemotions: "data/processed/goemotions.csv"