model:
  name: "ImprovedEmotionModel"

image_encoder:
  backbone: "resnet18"
  pretrained: true
  output_dim: 256

audio_encoder:
  rnn_units: 128
  num_layers: 2
  bidirectional: true
  dropout: 0.2

text_encoder:
  embedding_dim: 300
  hidden_dim: 128
  rnn_type: "lstm"
  bidirectional: true

fusion:
  attention_heads: 4
  dropout: 0.3
  fusion_dim: 512

output_layer:
  num_classes: 5
  activation: "softmax"

regularization:
  dropout_rate: 0.5
  layer_norm: true
