# configs/model_config.yaml

model:
  num_emotions: 7
  dropout: 0.5
  rnn_hidden: 256  # Hidden size for the bidirectional RNN

attention:
  num_heads: 8
  dropout: 0.1

fusion:
  modality_dim: 256  # Dimension for modality features
  mlp_hidden: 512    # Hidden dimension in fusion MLP

image_encoder:
  initial_channels: 64
  channels: [64, 128, 256]  # Channel progression in residual blocks

audio_encoder:
  initial_channels: 64
  kernel_size: 7
  channels: [64, 128, 256]  # Channel progression in 1D residual blocks

text_encoder:
  vocab_size: 30522         # BERT vocabulary size
  embedding_dim: 128
  rnn_layers: 1
  bidirectional: true