model:
  num_emotions: 7
  rnn_hidden: 256

dropouts:
  image_encoder: 0.2
  audio_encoder: 0.2
  text_encoder: 0.3
  fusion: 0.3
  attention: 0.1
  classifier: 0.2

attention:
  num_heads: 8
  dropout: 0.1

fusion:
  modality_dim: 256
  mlp_hidden: 512

image_encoder:
  initial_channels: 64
  channels: [64, 128, 256]

audio_encoder:
  initial_channels: 64
  kernel_size: 7
  channels: [64, 128, 256]

text_encoder:
  vocab_size: 30522
  embedding_dim: 128
  rnn_layers: 1
  bidirectional: true