training:
  batch_size: 32
  num_workers: 4
  learning_rate: 1e-4
  weight_decay: 5e-4
  epochs: 50
  patience: 5
  scheduler_patience: 5
  grad_clip: 0.5
  warmup_steps: 2000

data:
  train_ratio: 0.8
  pin_memory: true
  persistent_workers: true

optimization:
  amp: true
  cuda_non_blocking: true
  accumulation_steps: 4

logging:
  log_dir: "logs"
  checkpoints_dir: "checkpoints"
  plots_dir: "plots"
  tensorboard_dir: "tensorboard"

model_config:
  input_shape: [1, 224, 224]  # Added for export_model function